const factions = [
    {
        id: 'brotherhood-of-steel',
        name: 'Brotherhood of Steel',
        icon: '⚙️',
        tagline: 'Ad Victoriam!',
        description: 'The Brotherhood of Steel is a quasi-religious technocratic military order founded by former U.S. Army officer Roger Maxson shortly after the Great War. They are dedicated to the preservation and regulation of pre-war technology, believing that the misuse of technology led to the destruction of the old world.',
        history: 'Founded in 2077 at Mariposa Military Base in California, the Brotherhood emerged when Captain Roger Maxson led a mutiny after discovering the horrific FEV experiments being conducted on military prisoners. After the bombs fell, they trekked to Lost Hills bunker, establishing the foundations of the Brotherhood. Over the centuries, they spread across the wasteland, with chapters forming in the Midwest, East Coast, and Mojave.',
        ideology: 'The Brotherhood believes in preserving technology and preventing its misuse by those they deem unworthy. They collect, study, and hoard pre-war tech, particularly weapons. While some chapters focus on protecting wastelanders, others prioritize their mission above all else, refusing to share technology with outsiders.',
        headquarters: ['Lost Hills (West Coast)', 'The Citadel (East Coast)', 'The Prydwen (Mobile)', 'Hidden Valley (Mojave)'],
        notableMembers: ['Elder Maxson', 'Paladin Danse', 'Elder Lyons', 'Scribe Rothchild', 'Veronica Santangelo', 'Christine Royce', 'Maximus (TV Series)', 'Knight Titus (TV Series)'],
        games: ['Fallout 1', 'Fallout 2', 'Fallout 3', 'Fallout New Vegas', 'Fallout 4', 'Fallout 76'],
        alignment: 'Variable',
        alignmentClass: 'alignment-neutral',
        strengths: ['Advanced technology', 'Power Armor expertise', 'Military discipline', 'Vertibird fleet'],
        weaknesses: ['Isolationist tendencies', 'Limited recruitment', 'Resource-intensive operations', 'Internal divisions'],
        tvSeries: {
            appears: true,
            seasons: [1, 2],
            description: 'The Brotherhood plays a major role in the Prime Video series. Maximus (played by Aaron Moten) begins as a Squire and rises through the ranks after assuming the identity of the fallen Knight Titus. The Brotherhood operates with a cult-like hierarchy, with Knights wearing Power Armor. By the end of Season 1, Maximus is promoted to Knight after the battle at Griffith Observatory and is credited with acquiring cold fusion technology for the Brotherhood.',
            keyCharacters: ['Maximus (Aaron Moten)', 'Knight Titus', 'Dane']
        }
    },
    {
        id: 'ncr',
        name: 'New California Republic',
        icon: '🐻',
        tagline: 'For the Republic!',
        description: 'The New California Republic is a democratic federation modeling itself after the pre-war United States. Founded in the town of Shady Sands, it has grown to become one of the largest and most organized civilizations in the post-apocalyptic world, spanning much of California and beyond.',
        history: 'The NCR was founded in 2189, emerging from the small community of Shady Sands that was established by Vault 15 dwellers. Under the leadership of Aradesh and later his daughter Tandi (who served as president for 52 years), the NCR grew from a small town into a sprawling nation. By the events of Fallout: New Vegas, it boasts a population of over 700,000 citizens.',
        ideology: 'The NCR promotes democratic values, individual rights, and rule of law. They seek to bring civilization, order, and safety to the wasteland through expansion and integration of settlements. However, their rapid growth has led to bureaucratic inefficiency, corruption, and imperialistic tendencies.',
        headquarters: ['Shady Sands (Capital - Destroyed)', 'The Hub', 'Camp McCarran', 'Hoover Dam', 'Griffith Observatory (TV Series)'],
        notableMembers: ['President Tandi', 'President Kimball', 'General Oliver', 'Chief Hanlon', 'Colonel Hsu', 'Ranger Ghost', 'Lee Moldaver (TV Series)'],
        games: ['Fallout 2', 'Fallout New Vegas'],
        alignment: 'Lawful Neutral',
        alignmentClass: 'alignment-neutral',
        strengths: ['Large population', 'Industrial capacity', 'Democratic legitimacy', 'Trained military', 'NCR Rangers'],
        weaknesses: ['Overextension', 'Bureaucracy', 'Corruption', 'Supply line issues', 'Political infighting'],
        tvSeries: {
            appears: true,
            seasons: [1, 2],
            description: 'The TV series reveals a devastating canonical event: sometime after the events of Fallout: New Vegas (2281), Shady Sands was destroyed by a nuclear bomb dropped by Vault 33 Overseer Hank MacLean. This occurred because his wife Rose and children fled to live there with Lee Moldaver. By 2296, the NCR is greatly diminished and led by Moldaver from the Griffith Observatory. The Fall of Shady Sands caused significant controversy among fans regarding the timeline.',
            keyCharacters: ['Lee Moldaver (Frances Turner)', 'Rose MacLean', 'NCR Soldiers']
        }
    },
    {
        id: 'caesars-legion',
        name: "Caesar's Legion",
        icon: '🦅',
        tagline: 'True to Caesar!',
        description: "Caesar's Legion is a ruthless slaver society and totalitarian dictatorship founded by Edward Sallow, who renamed himself Caesar. Based on the ancient Roman Empire, the Legion has conquered and assimilated over 86 tribes across the American Southwest through brutal warfare and cultural erasure.",
        history: "Founded in 2247 when former Follower of the Apocalypse Edward Sallow encountered the Blackfoot tribe in Arizona. Using his knowledge of history and warfare, he transformed them into a conquering army. Sallow, now Caesar, built his Legion by crushing or absorbing dozens of tribes, erasing their identities and forging them into fanatically loyal soldiers.",
        ideology: "The Legion believes in absolute authority, martial valor, and the subjugation of the weak. They reject modern technology (except for medicine and weapons), enslave women, and ban chems and alcohol. Caesar views democracy and individualism as weaknesses that led to the old world's destruction.",
        headquarters: ['Fortification Hill', 'The Fort', 'Flagstaff (Eastern Capital)'],
        notableMembers: ['Caesar', 'Legate Lanius', 'Vulpes Inculta', 'Lucius', 'Aurelius of Phoenix', 'Cursor Lucullus'],
        games: ['Fallout New Vegas'],
        alignment: 'Lawful Evil',
        alignmentClass: 'alignment-hostile',
        strengths: ['Fanatical loyalty', 'Brutal discipline', 'Large slave army', 'No supply chain dependency', 'Effective intelligence network'],
        weaknesses: ['Cult of personality', 'No succession plan', 'Technological regression', 'Treatment of women limits workforce', 'Unsustainable expansion'],
        tvSeries: {
            appears: true,
            seasons: [2],
            description: "Caesar's Legion makes their TV series debut in Season 2, which takes place in and around New Vegas. As one of the three major factions vying for control of New Vegas and the Hoover Dam in the games, they appear as antagonists in the show. The Legion remains one of the most brutal and controversial factions in the Fallout universe, and their presence suggests the show will explore the power struggle over the Mojave.",
            keyCharacters: ['Legion Soldiers']
        }
    },
    {
        id: 'institute',
        name: 'The Institute',
        icon: '🔬',
        tagline: 'Mankind - Redefined',
        description: 'The Institute is an advanced scientific organization hidden beneath the ruins of the Commonwealth Institute of Technology (C.I.T.) in Boston. They are the creators of the synthetic humanoids known as Synths and possess technology far beyond anything else in the wasteland.',
        history: 'The Institute evolved from C.I.T. survivors who retreated underground after the Great War. Over two centuries, they developed extraordinary technology, including teleportation and synthetic humans. They view themselves as humanity\'s best hope for the future, though their methods and secrecy have made them feared and hated throughout the Commonwealth.',
        ideology: 'The Institute believes that the surface world is beyond saving and that humanity\'s future lies in scientific advancement underground. They view Synths as tools rather than beings, and see surface dwellers as primitive. Their long-term goal is to eventually reclaim the surface through superior technology.',
        headquarters: ['The Institute (Underground Complex beneath C.I.T. Ruins)'],
        notableMembers: ['Father/Shaun', 'Dr. Madison Li', 'Dr. Zimmer', 'Dr. Ayo', 'Coursers'],
        games: ['Fallout 3', 'Fallout 4'],
        alignment: 'True Neutral',
        alignmentClass: 'alignment-neutral',
        strengths: ['Superior technology', 'Synth production', 'Teleportation capability', 'Scientific expertise', 'Hidden location'],
        weaknesses: ['Isolation from surface', 'Ethical blind spots', 'Public fear and hatred', 'Dependent on power supply', 'Internal disagreements']
    },
    {
        id: 'railroad',
        name: 'The Railroad',
        icon: '🚂',
        tagline: 'We are the Free',
        description: 'The Railroad is a secretive organization dedicated to freeing Synths from the Institute and helping them escape to safety. Named after the historical Underground Railroad that helped slaves escape to freedom, they believe that Synths are sentient beings deserving of liberty.',
        history: 'The Railroad\'s origins are unclear, but they have operated in the Commonwealth for decades. They were nearly destroyed by the Institute multiple times, forcing them to move headquarters repeatedly. Despite heavy losses, they continue their mission to liberate Synths and give them new identities.',
        ideology: 'The Railroad believes that third-generation Synths are fully sentient beings with consciousness, emotions, and free will. They argue that keeping Synths enslaved is morally equivalent to human slavery and must be opposed. Some members prioritize Synth freedom above all else, while others see it as part of broader humanitarian work.',
        headquarters: ['The Old North Church (Current)', 'Various safehouses throughout the Commonwealth'],
        notableMembers: ['Desdemona', 'Deacon', 'Tinker Tom', 'Glory', 'Patriot/Liam Binet', 'Dr. Carrington'],
        games: ['Fallout 4'],
        alignment: 'Chaotic Good',
        alignmentClass: 'alignment-friendly',
        strengths: ['Extensive spy network', 'Memory wipe technology', 'Dedicated agents', 'Synth allies', 'Hidden operation'],
        weaknesses: ['Small numbers', 'Limited resources', 'Narrow focus', 'Vulnerable to infiltration', 'Dependent on secrecy']
    },
    {
        id: 'minutemen',
        name: 'The Minutemen',
        icon: '🔔',
        tagline: 'At a minute\'s notice!',
        description: 'The Commonwealth Minutemen are a volunteer militia dedicated to protecting the settlements and people of the Commonwealth. Named after the historical Minutemen of the American Revolution, they respond to threats against communities and believe in helping anyone in need.',
        history: 'The Minutemen formed in 2180 when settlers needed protection from raiders and other threats. They grew to become the dominant protective force in the Commonwealth until their near-destruction at the Quincy Massacre, where Gunners overwhelmed them due to internal betrayal. A lone survivor and the Sole Survivor can rebuild them from nothing.',
        ideology: 'The Minutemen believe in mutual aid and community defense. Unlike other factions, they don\'t seek power or territory - they simply help those who need it. Their decentralized structure means settlements can govern themselves while still receiving protection.',
        headquarters: ['The Castle (Fort Independence)', 'Sanctuary Hills', 'Various allied settlements'],
        notableMembers: ['Preston Garvey', 'Colonel Hollis', 'General (The Sole Survivor)', 'Ronnie Shaw', 'Sturges'],
        games: ['Fallout 4'],
        alignment: 'Neutral Good',
        alignmentClass: 'alignment-friendly',
        strengths: ['Popular support', 'Decentralized structure', 'Artillery network', 'Moral legitimacy', 'Settlement resources'],
        weaknesses: ['Volunteer army', 'Limited training', 'No central authority', 'Vulnerable to internal betrayal', 'Resource dependent']
    },
    {
        id: 'enclave',
        name: 'The Enclave',
        icon: '🇺🇸',
        tagline: 'God Bless America',
        description: 'The Enclave are the self-proclaimed continuation of the pre-war United States government. Composed of descendants of government officials, military officers, and wealthy elites who survived the Great War in secure bunkers, they believe themselves to be the only "pure" humans left and seek to reclaim America.',
        history: 'The Enclave formed from members of the pre-war shadow government who retreated to the Poseidon Oil Rig before the bombs fell. For over a century, they planned their return, developing advanced technology and plotting to "purify" America of all mutated life - including most wastelanders. Their oil rig was destroyed by the Chosen One in 2242, and their East Coast remnants were defeated by the Brotherhood in 2277.',
        ideology: 'The Enclave believes that radiation and FEV have corrupted all surface dwellers, making them "mutants" unfit to inherit America. Only those with "pure" pre-war lineage deserve to survive. They planned to release modified FEV to kill all mutated life, allowing them to repopulate the continent.',
        headquarters: ['Poseidon Oil Rig (Destroyed)', 'Raven Rock (Destroyed)', 'Control Station ENCLAVE', 'Various bunkers'],
        notableMembers: ['President Richardson', 'President Eden', 'Colonel Autumn', 'Frank Horrigan', 'Sergeant Dornan', 'Dr. Siggi Wilzig (TV Series)'],
        games: ['Fallout 2', 'Fallout 3', 'Fallout 76'],
        alignment: 'Lawful Evil',
        alignmentClass: 'alignment-hostile',
        strengths: ['Most advanced technology', 'Power Armor superiority', 'Vertibird fleet', 'Military training', 'Pre-war resources'],
        weaknesses: ['Extremely limited numbers', 'Genocidal goals alienate allies', 'No recruitment pool', 'Multiple major defeats', 'Scattered remnants'],
        tvSeries: {
            appears: true,
            seasons: [1, 2],
            description: 'The Enclave appears briefly in Season 1, confirming they still exist in some form by 2296. Dr. Siggi Wilzig (played by Michael Emerson) is an Enclave scientist who escapes from a secret facility with valuable cold fusion technology stored in his head. Wilzig becomes disillusioned with the Enclave\'s unethical experiments on living beings, including super mutants and dogs, leading to his defection. The TV series hints that The Enclave will play a larger role in future seasons.',
            keyCharacters: ['Dr. Siggi Wilzig (Michael Emerson)', 'CX404 (Dogmeat)']
        }
    },
    {
        id: 'followers-of-apocalypse',
        name: 'Followers of the Apocalypse',
        icon: '📚',
        tagline: 'Knowledge is Power',
        description: 'The Followers of the Apocalypse are a humanitarian organization dedicated to education, medicine, and helping the wasteland rebuild without repeating the mistakes of the past. They provide free medical care, literacy programs, and scientific knowledge to anyone who needs it.',
        history: 'Founded in the Boneyard (Los Angeles) after the Great War, the Followers dedicated themselves to understanding why the old world destroyed itself and preventing it from happening again. They taught farming, medicine, and literacy to wastelanders. Ironically, one of their members, Edward Sallow, would later become Caesar and found the Legion.',
        ideology: 'The Followers believe that knowledge should be shared freely and that understanding the past is key to building a better future. They oppose hoarding technology (putting them at odds with the Brotherhood) and imperialism (opposing both NCR expansion and the Legion). They are pacifists when possible but will defend themselves.',
        headquarters: ['Old Mormon Fort (New Vegas)', 'Boneyard Library (Los Angeles)', 'Various clinics and camps'],
        notableMembers: ['Julie Farkas', 'Arcade Gannon', 'Edward Sallow (defected)', 'Emily Ortal', 'Nicole'],
        games: ['Fallout 1', 'Fallout 2', 'Fallout New Vegas'],
        alignment: 'Neutral Good',
        alignmentClass: 'alignment-friendly',
        strengths: ['Medical expertise', 'Historical knowledge', 'Popular goodwill', 'Extensive network', 'Ideological dedication'],
        weaknesses: ['Pacifist tendencies', 'Limited resources', 'No military capability', 'Easily exploited', 'Stretched thin']
    },
    {
        id: 'super-mutants',
        name: 'Super Mutants',
        icon: '💪',
        tagline: 'The Master\'s Army',
        description: 'Super Mutants are humans transformed by the Forced Evolutionary Virus (FEV) into large, muscular, and often aggressive mutants. While not a unified faction, the original Super Mutants on the West Coast were organized under the Master as his army to forcibly evolve humanity.',
        history: 'The first Super Mutants were created at Mariposa Military Base when the Master, a former human named Richard Grey, fell into a vat of FEV and merged with the facility\'s computers. He created an army to dip humans in FEV, believing forced evolution was humanity\'s salvation. After the Master\'s defeat in 2162, his army scattered. Different strains of Super Mutants emerged later from other FEV sources.',
        ideology: 'The Master believed Super Mutants were the next stage of human evolution and sought to "unify" humanity by transforming everyone. After his defeat, most Super Mutants lack unified ideology - some are mindlessly violent, others seek peaceful coexistence. Jacobstown in the Mojave represents mutants seeking isolation and peace.',
        headquarters: ['Mariposa Military Base (Destroyed)', 'The Cathedral/LA Vault (Destroyed)', 'Jacobstown (Peaceful settlement)', 'Various camps'],
        notableMembers: ['The Master', 'Marcus', 'Fawkes', 'Strong', 'Lily Bowen', 'The Nightkin', 'Neil'],
        games: ['Fallout 1', 'Fallout 2', 'Fallout 3', 'Fallout New Vegas', 'Fallout 4', 'Fallout 76'],
        alignment: 'Variable',
        alignmentClass: 'alignment-neutral',
        strengths: ['Superhuman strength', 'Radiation immunity', 'Disease resistance', 'Long lifespan', 'Intimidating presence'],
        weaknesses: ['Sterility', 'Mental degradation (many)', 'Feared and hated', 'No recruitment (requires FEV)', 'Internal conflicts'],
        tvSeries: {
            appears: true,
            seasons: [1],
            description: 'Super Mutants appear in the TV series, primarily shown as subjects of Enclave experimentation. Dr. Siggi Wilzig\'s disgust at the Enclave\'s experiments on Super Mutants and other living beings is part of what drives his defection. They serve as a reminder of the wasteland\'s dangers and the unethical experiments various factions conduct.',
            keyCharacters: ['Various Super Mutants']
        }
    },
    {
        id: 'ghouls',
        name: 'Ghouls',
        icon: '☠️',
        tagline: 'Smoothskin...',
        description: 'Ghouls are humans who were exposed to massive amounts of radiation but instead of dying, underwent ghoulification - a mutation that grants extreme longevity and radiation immunity at the cost of gradual physical decay. While not a unified faction, ghouls share common experiences of discrimination and survival.',
        history: 'Ghouls emerged after the Great War when humans exposed to radiation mutated rather than died. Some ghouls have lived for over 200 years, retaining their memories and personalities from before the war. However, many ghouls eventually go "feral," losing their minds and becoming aggressive. Non-feral ghouls face discrimination from humans who fear or hate them.',
        ideology: 'Ghouls have no unified ideology - they are simply mutated humans trying to survive. Some integrate into human society, others form ghoul-only communities like Underworld in DC or Necropolis. Many pre-war ghouls struggle with memories of the old world and watching everyone they knew die.',
        headquarters: ['Underworld (DC)', 'Necropolis (Destroyed)', 'Goodneighbor (Commonwealth)', 'Various settlements'],
        notableMembers: ['The Ghoul/Cooper Howard (TV Series)', 'Hancock', 'Raul Tejada', 'Dean Domino', 'Eddie Winter', 'Desmond Lockheart', 'Set'],
        games: ['Fallout 1', 'Fallout 2', 'Fallout 3', 'Fallout New Vegas', 'Fallout 4', 'Fallout 76'],
        alignment: 'Variable',
        alignmentClass: 'alignment-neutral',
        strengths: ['Extreme longevity', 'Radiation immunity', 'Radiation healing', 'Pre-war knowledge (some)', 'Underestimated'],
        weaknesses: ['Social discrimination', 'Risk of going feral', 'Physical deterioration', 'Need special medicine', 'Feared by humans'],
        tvSeries: {
            appears: true,
            seasons: [1, 2],
            description: 'The Ghoul, born Cooper Howard (played by Walton Goggins), is one of the three main protagonists of the TV series. Once a famous Hollywood actor and Vault-Tec spokesman before the war, Cooper was transformed into a ghoul after the bombs fell and has spent over 200 years as a ruthless bounty hunter. The series explores his tragic backstory through flashbacks, showing his happy pre-war life with his wife Barb (a Vault-Tec executive) and daughter Janey. He must regularly take medicine to prevent going feral. Goggins received an Emmy nomination for Outstanding Lead Actor for his performance.',
            keyCharacters: ['The Ghoul/Cooper Howard (Walton Goggins)', 'Various Feral Ghouls']
        }
    },
    {
        id: 'vault-dwellers',
        name: 'Vault Dwellers',
        icon: '🔵',
        tagline: 'Okey Dokey!',
        description: 'Vault Dwellers are the inhabitants of Vault-Tec\'s underground fallout shelters. Having lived in isolation for generations, most Vault Dwellers are naive about the dangers of the wasteland but often prove resourceful when forced to venture outside. Many legendary wastelanders began as Vault Dwellers.',
        history: 'When the bombs fell in 2077, those fortunate (or unfortunate) enough to be selected entered the Vaults. For over 200 years, Vault Dwellers lived in their sealed underground communities, following the Overseer\'s rules and believing they would one day reclaim the surface. The reality was that most Vaults were cruel experiments, and those who emerged often found the wasteland very different from what they expected.',
        ideology: 'Vault Dwellers are typically taught to believe in order, community, and the eventual reclamation of America. They often cling to pre-war values and are shocked by the wasteland\'s brutality. The "Golden Rule" - treating others as you wish to be treated - is emphasized in many Vaults, though this naivety can be dangerous.',
        headquarters: ['Various Vaults across America', 'Vault 33 (TV Series)', 'Vault 13', 'Vault 101', 'Vault 111'],
        notableMembers: ['The Vault Dweller (Fallout 1)', 'The Chosen One (Fallout 2)', 'The Lone Wanderer (Fallout 3)', 'The Sole Survivor (Fallout 4)', 'Lucy MacLean (TV Series)', 'Norm MacLean (TV Series)'],
        games: ['Fallout 1', 'Fallout 2', 'Fallout 3', 'Fallout 4', 'Fallout 76'],
        alignment: 'Variable',
        alignmentClass: 'alignment-neutral',
        strengths: ['Education', 'Technical skills', 'Community bonds', 'Pre-war knowledge', 'Adaptability'],
        weaknesses: ['Naive about wasteland', 'Sheltered upbringing', 'Culture shock', 'May not know survival skills', 'Trust too easily'],
        tvSeries: {
            appears: true,
            seasons: [1, 2],
            description: 'Lucy MacLean (played by Ella Purnell), the show\'s main protagonist, is a Vault Dweller from Vault 33 in the Los Angeles area. When raiders attack her Vault and kidnap her father Hank (the Overseer), she ventures into the wasteland for the first time. Lucy embodies the classic Vault Dweller traits - optimistic, believing in the Golden Rule, and shocked by the wasteland\'s brutality. Her brother Norm remains in the Vault and uncovers the dark truth about Vaults 31-33. The series shows how Lucy\'s idealism is tested and changed by her experiences.',
            keyCharacters: ['Lucy MacLean (Ella Purnell)', 'Norm MacLean (Moisés Arias)', 'Hank MacLean (Kyle MacLachlan)', 'Various Vault 33 residents']
        }
    },
    {
        id: 'raiders',
        name: 'Raiders',
        icon: '💀',
        tagline: 'Take What You Want',
        description: 'Raiders are the catch-all term for the countless gangs of bandits, murderers, and criminals that plague the wasteland. While not a unified faction, they represent one of the most common threats to survival, attacking travelers and settlements for supplies, slaves, or simple sadistic pleasure.',
        history: 'Raiders emerged almost immediately after the Great War as desperate survivors turned to violence. Over the generations, raider culture developed its own brutal traditions. Some gangs are organized crime operations; others are barely-functioning groups of addicts. A few, like the Nuka-World raiders, have built significant power bases.',
        ideology: 'Most raiders subscribe to a might-makes-right philosophy, taking what they want from those too weak to stop them. Some gangs have developed unique cultures - the Fiends worship chems, the Forged worship fire, the Pack embrace animal savagery. The most successful raiders often transition into protection rackets or territorial control.',
        headquarters: ['Varies by gang - abandoned buildings, caves, pre-war structures'],
        notableMembers: ['Motor-Runner (Fiends)', 'Colter (Nuka-World)', 'Jared (Commonwealth)', 'Cook-Cook (Fiends)', 'The Disciples/Pack/Operators leaders'],
        games: ['Fallout 1', 'Fallout 2', 'Fallout 3', 'Fallout New Vegas', 'Fallout 4', 'Fallout 76'],
        alignment: 'Chaotic Evil',
        alignmentClass: 'alignment-hostile',
        strengths: ['Numerous', 'No rules of engagement', 'Unpredictable', 'Know the territory', 'Desperate fighters'],
        weaknesses: ['Disorganized', 'No supply lines', 'Chem addiction', 'Constant infighting', 'Everyone hates them'],
        tvSeries: {
            appears: true,
            seasons: [1, 2],
            description: 'Raiders play a significant role in the TV series. The inciting incident of Season 1 occurs when raiders attack Vault 33, killing many residents and kidnapping Overseer Hank MacLean. These raiders are revealed to be working with Lee Moldaver and the remnants of the NCR. Throughout the series, various raider groups are encountered in the wasteland, showcasing the brutal reality of post-apocalyptic survival.',
            keyCharacters: ['Various Raider gangs']
        }
    },
    {
        id: 'vault-tec',
        name: 'Vault-Tec Corporation',
        icon: '🏛️',
        tagline: 'Prepare for the Future!',
        description: 'Vault-Tec Corporation was the pre-war company contracted to build the Vault system that would shelter Americans from nuclear war. In truth, most Vaults were designed as unethical social experiments, with Vault-Tec using the apocalypse as an opportunity for twisted research.',
        history: 'Founded before the Great War, Vault-Tec received government contracts to build 122 Vaults across America. While marketed as survival shelters, the real purpose was to conduct experiments on isolated populations - testing everything from overcrowding to cloning to total dictatorial control. The company\'s leadership had access to their own private Vault.',
        ideology: 'Vault-Tec\'s true ideology was the pursuit of knowledge regardless of ethics, funded by disaster capitalism. They knowingly built faulty Vaults, subjected thousands to horrific experiments, and may have even played a role in starting the Great War. Some researchers believed they were helping humanity; leadership just wanted data.',
        headquarters: ['Vault-Tec HQ (Various locations)', 'Secret Vault', 'Control Vaults', 'Vaults 31, 32, 33 (TV Series)'],
        notableMembers: ['Vault-Tec Rep', 'Stanislaus Braun', 'Various Overseers', 'The Board', 'Barb Howard (TV Series)', 'Bud Askins (TV Series)', 'Hank MacLean (TV Series)'],
        games: ['Fallout 1', 'Fallout 2', 'Fallout 3', 'Fallout New Vegas', 'Fallout 4', 'Fallout 76'],
        alignment: 'Lawful Evil',
        alignmentClass: 'alignment-hostile',
        strengths: ['Pre-war resources', 'Advanced technology', 'Vault network', 'Extensive data', 'Government backing'],
        weaknesses: ['Company effectively dissolved', 'Experiments often failed', 'No post-war presence', 'Universally reviled', 'Vaults mostly failed'],
        tvSeries: {
            appears: true,
            seasons: [1, 2],
            description: 'Vault-Tec is central to the TV series plot. Through flashbacks, we see Cooper Howard\'s wife Barb Howard was a Vault-Tec executive who attended a secret meeting where corporate moguls planned to use Vaults for social experiments. Most shockingly, it\'s revealed that Vault-Tec may have started the Great War themselves when Barb suggested they should "take the first step" since their plans required nuclear apocalypse. The series also reveals Vaults 31-33 were interconnected experiments, with Vault 31 containing cryogenically frozen Vault-Tec executives (including Hank MacLean) who would emerge to lead the other Vaults.',
            keyCharacters: ['Barb Howard (Frances Turner)', 'Bud Askins', 'Hank MacLean (Kyle MacLachlan)', 'Lucy MacLean (Ella Purnell)', 'Norm MacLean']
        }
    },
    {
        id: 'mr-house',
        name: 'Mr. House / New Vegas',
        icon: '♠️',
        tagline: 'The House Always Wins',
        description: 'Robert Edwin House is the mysterious ruler of New Vegas, a pre-war industrialist who predicted the Great War and prepared for it. Using his vast wealth and technological genius, he preserved Las Vegas from nuclear destruction and now rules it as an autocratic businessman, seeking to restore civilization through capitalism and technology.',
        history: 'House was the founder and CEO of RobCo Industries before the war. He predicted nuclear war would occur by 2077 and spent his fortune preparing - defensive systems to shoot down missiles, an army of Securitrons, and life support technology to keep himself alive. He saved Vegas from 68 of the 77 warheads targeting it and spent centuries preparing his return.',
        ideology: 'House believes in progress through technology and enlightened autocracy. He sees democracy as inefficient and tribalism as primitive. His goal is to use New Vegas\'s wealth to eventually develop spaceflight and expand humanity to the stars within 200 years. He views himself as the only one capable of leading humanity forward.',
        headquarters: ['Lucky 38 Casino (New Vegas Strip)'],
        notableMembers: ['Mr. House', 'Victor', 'Jane', 'The Three Families leaders', 'Securitrons'],
        games: ['Fallout New Vegas'],
        alignment: 'Lawful Neutral',
        alignmentClass: 'alignment-neutral',
        strengths: ['Genius intellect', 'Securitron army', 'Economic control', 'Pre-war technology', 'Long-term planning'],
        weaknesses: ['Physically helpless', 'Dependent on technology', 'Single point of failure', 'Emotionally detached', 'Underestimates others'],
        tvSeries: {
            appears: true,
            seasons: [1, 2],
            description: 'Mr. House appears briefly in Season 1 flashbacks as one of the corporate executives at the secret Vault-Tec meeting where they discussed using Vaults for experiments. In Season 2, he takes center stage as the show moves to New Vegas. Justin Theroux portrays House, and the teaser trailer shows a near-perfect replica of his Lucky 38 penthouse headquarters with House himself active and operational. At the end of Season 1, Lucy, The Ghoul, and CX404 are seen heading toward New Vegas to find Hank MacLean.',
            keyCharacters: ['Mr. House (Justin Theroux)']
        }
    },
    {
        id: 'gunners',
        name: 'The Gunners',
        icon: '🎯',
        tagline: 'Professional. Deadly. Expensive.',
        description: 'The Gunners are a ruthless mercenary organization operating throughout the Commonwealth. Unlike common raiders, they are professional soldiers with military discipline, advanced equipment, and a corporate structure. They take contracts from anyone who can pay, regardless of ethics.',
        history: 'The Gunners\' origins are unclear, but they may have evolved from pre-war military units or private security. They operate like a corporation, with ranks, contracts, and a clear chain of command. They maintain several fortified bases and are known to betray former allies, including the Minutemen at Quincy.',
        ideology: 'The Gunners are purely mercenary - morality is irrelevant, only profit matters. They\'ll protect a settlement one day and burn it the next if the price is right. Their professionalism makes them more dangerous than raiders, as they plan operations carefully and maintain military discipline.',
        headquarters: ['Gunners Plaza (HQ)', 'Hub City Auto Wreckers', 'Various fortified positions'],
        notableMembers: ['Captain Wes', 'Clint (Traitor)', 'Barnes', 'Winlock'],
        games: ['Fallout 4'],
        alignment: 'Lawful Evil',
        alignmentClass: 'alignment-hostile',
        strengths: ['Military training', 'Advanced weapons', 'Organization', 'Discipline', 'Strategic planning'],
        weaknesses: ['Only loyal to money', 'Make enemies easily', 'Overconfident', 'No popular support', 'Limited recruitment']
    },
    {
        id: 'children-of-atom',
        name: 'Children of Atom',
        icon: '☢️',
        tagline: 'Behold! He is coming with the clouds!',
        description: 'The Children of Atom are a religious cult that worships radiation and nuclear weapons as divine. They believe the Great War was a holy event that released "Atom\'s Glow" into the world, and that radiation will eventually divide them into infinite universes where they can live forever.',
        history: 'The Church of the Children of Atom was founded in Megaton, a settlement built around an undetonated nuclear bomb. The religion spread across the wasteland, with major congregations in the Commonwealth and Far Harbor. Their beliefs make them immune to fear of radiation, and some members develop genuine radiation resistance.',
        ideology: 'The Children believe radiation is sacred and that atoms contain multiple universes. When someone dies by radiation, they believe the person is "divided" into these universes, achieving a form of immortality. They seek out irradiated areas as holy sites and oppose those who would remove radiation from the world.',
        headquarters: ['Crater of Atom (Commonwealth)', 'The Nucleus (Far Harbor)', 'Megaton (Founded here)'],
        notableMembers: ['Confessor Cromwell', 'High Confessor Tektus', 'Grand Zealot Richter', 'Mother Isolde', 'Brother Henri'],
        games: ['Fallout 3', 'Fallout 4', 'Fallout 76'],
        alignment: 'Chaotic Neutral',
        alignmentClass: 'alignment-neutral',
        strengths: ['Radiation immunity (some)', 'Fanatical devotion', 'No fear of death', 'Access to irradiated areas', 'Gamma gun technology'],
        weaknesses: ['Viewed as insane', 'Self-destructive beliefs', 'Internal schisms', 'Limited resources', 'Make enemies easily']
    },
    {
        id: 'great-khans',
        name: 'The Great Khans',
        icon: '🏍️',
        tagline: 'Strength Through Unity',
        description: 'The Great Khans are a warrior tribe descended from the Vault 15 survivors, known for their fierce independence, drug manufacturing, and Mongol-inspired culture. Once powerful raiders, they were devastated at Bitter Springs and now struggle to survive in the Mojave.',
        history: 'The original Khans were founded by one of the groups from Vault 15, becoming feared raiders until their destruction by the Vault Dweller. The New Khans rose and fell. The Great Khans emerged as the third iteration, establishing themselves in the Mojave until the NCR massacred their camp at Bitter Springs, killing many civilians and breaking their power.',
        ideology: 'The Khans value strength, freedom, and tribal loyalty above all. They refuse to submit to any outside authority and maintain their own traditions and identity. Their drug manufacturing is seen as a path to independence. Despite their violent history, they have a strong code of honor within the tribe.',
        headquarters: ['Red Rock Canyon', 'Bitter Springs (Former)', 'Various camps'],
        notableMembers: ['Papa Khan', 'Regis', 'Jack', 'Diane', 'Karl', 'Melissa Lewis'],
        games: ['Fallout 1', 'Fallout 2', 'Fallout New Vegas'],
        alignment: 'True Neutral',
        alignmentClass: 'alignment-neutral',
        strengths: ['Fierce warriors', 'Drug production income', 'Strong tribal bonds', 'Survival skills', 'Motorcycle mobility'],
        weaknesses: ['Devastated population', 'Surrounded by enemies', 'Limited territory', 'Chem addiction problems', 'Pride prevents alliances']
    },
    {
        id: 'boomers',
        name: 'The Boomers',
        icon: '💣',
        tagline: 'Peace Through Superior Firepower',
        description: 'The Boomers are an isolationist tribe descended from Vault 34 dwellers who became obsessed with weapons and explosives. They inhabit Nellis Air Force Base, where they maintain a massive arsenal including artillery and a restored B-29 bomber, attacking any outsiders who approach.',
        history: 'The Boomers\' ancestors were Vault 34 residents who left due to conflicts over the Vault\'s armory. They settled at Nellis Air Force Base, using its artillery to keep everyone away. For generations, they\'ve had no contact with the outside world, sustaining themselves through salvage, hunting, and farming while perfecting their weapons.',
        ideology: 'The Boomers believe in absolute isolationism and firepower as the solution to all problems. They distrust all outsiders and shoot on sight. However, they\'re not malicious - they simply want to be left alone. If someone earns their trust, they can be loyal allies with devastating military capability.',
        headquarters: ['Nellis Air Force Base'],
        notableMembers: ['Mother Pearl', 'Loyal', 'Jack', 'Raquel', 'Pete'],
        games: ['Fallout New Vegas'],
        alignment: 'True Neutral',
        alignmentClass: 'alignment-neutral',
        strengths: ['Massive artillery', 'B-29 bomber', 'Military base', 'Self-sufficient', 'Explosives expertise'],
        weaknesses: ['Extreme isolationism', 'Small population', 'Limited gene pool', 'No outside trade', 'Surrounded by enemies']
    },
    {
        id: 'responders',
        name: 'The Responders',
        icon: '🚑',
        tagline: 'Help Each Other, Help Ourselves',
        description: 'The Responders were a volunteer emergency response organization in Appalachia composed of former first responders - firefighters, police, paramedics, and volunteers. They dedicated themselves to helping survivors of the Great War until they were wiped out by the Scorched Plague.',
        history: 'Formed shortly after the bombs fell from surviving emergency personnel in Appalachia, the Responders established aid stations, trained survivors, and fought to maintain order. They were one of the most organized and benevolent factions in the region until the Scorched Plague overwhelmed them. By 2102, only their equipment, training materials, and automated systems remained.',
        ideology: 'The Responders believed in the basic goodness of humanity and that communities could rebuild through mutual aid. They trained anyone willing to help and freely shared supplies and knowledge. Their motto reflected their core belief that helping others was the key to survival.',
        headquarters: ['Flatwoods', 'Morgantown Airport', 'Charleston Emergency Center (Destroyed)'],
        notableMembers: ['Maria Chavez', 'Jeff Nakamura', 'Melody Larkin', 'Kesha McDermott'],
        games: ['Fallout 76'],
        alignment: 'Lawful Good',
        alignmentClass: 'alignment-friendly',
        strengths: ['Professional training', 'Medical expertise', 'Community trust', 'Organized structure', 'Educational resources'],
        weaknesses: ['Depleted by plague', 'Overstretched resources', 'Non-combatant focus', 'Effectively extinct', 'Relied on volunteers']
    },
    {
        id: 'free-states',
        name: 'The Free States',
        icon: '🗽',
        tagline: 'Don\'t Tread On Me',
        description: 'The Free States were a secessionist movement in Appalachia composed of survivalists and libertarians who distrusted the federal government. They built a network of bunkers before the war and initially thrived, but internal conflicts and external threats eventually destroyed them.',
        history: 'Before the Great War, the Free States movement predicted nuclear conflict and seceded from the Union, building bunkers throughout the Mire region. When the bombs fell, they survived better than most. However, paranoia, distrust of outsiders, and eventual conflict with the Scorched and other factions led to their demise.',
        ideology: 'The Free States believed in radical individual liberty, distrust of all government, and extreme self-reliance. They saw the pre-war government as tyrannical and viewed the apocalypse as vindication of their beliefs. They valued freedom above safety and would rather die free than live under any authority.',
        headquarters: ['Harpers Ferry', 'Abbie\'s Bunker', 'Various bunkers in The Mire'],
        notableMembers: ['Raleigh Clay', 'Abbie Singh', 'Sam Blackwell', 'Ella Ames'],
        games: ['Fallout 76'],
        alignment: 'Chaotic Neutral',
        alignmentClass: 'alignment-neutral',
        strengths: ['Prepared bunkers', 'Survival expertise', 'Technology skills', 'Self-sufficient', 'Predicted the war'],
        weaknesses: ['Paranoid', 'Refused cooperation', 'Small numbers', 'Disunited', 'Extinct']
    },
    {
        id: 'disciples-of-atom',
        name: 'The Disciples',
        icon: '🔪',
        tagline: 'Bleed for the Pack',
        description: 'The Disciples are one of three raider gangs that conquered Nuka-World under Overboss Colter. They are sadistic killers who worship death and pain, decorating their territory with corpses and taking pleasure in torture. Even other raiders consider them extreme.',
        history: 'The Disciples formed around a charismatic killer named Nisha who gathered like-minded individuals who found joy in violence. They joined the coalition that took Nuka-World, claiming Fizztop Mountain as their territory. They barely tolerate the other gangs and constantly push for more violence.',
        ideology: 'The Disciples believe that killing is an art form and that pain - both giving and receiving - brings enlightenment. They\'re not motivated by profit like the Operators or territory like the Pack, but by the sheer pleasure of violence. Death is their religion and blades are their sacrament.',
        headquarters: ['Fizztop Mountain (Nuka-World)'],
        notableMembers: ['Nisha', 'Dixie', 'Savoy'],
        games: ['Fallout 4 (Nuka-World DLC)'],
        alignment: 'Chaotic Evil',
        alignmentClass: 'alignment-hostile',
        strengths: ['No fear', 'Intimidation', 'Stealth skills', 'Blade expertise', 'Psychological warfare'],
        weaknesses: ['Unstable', 'Alienate allies', 'Self-destructive', 'No planning', 'Eventually turn on everyone']
    },
    {
        id: 'operators',
        name: 'The Operators',
        icon: '💰',
        tagline: 'Everything Has a Price',
        description: 'The Operators are one of three raider gangs in Nuka-World, distinguished by their business-like approach to raiding. They dress well, maintain discipline, and treat crime as a profession. To them, raiding is just business - nothing personal.',
        history: 'The Operators were founded by siblings Mags and William Black, who brought corporate structure to raiding. They joined the Nuka-World coalition seeing profit potential. Unlike the other gangs, they don\'t raid for thrills or territory but for caps, treating their operation like a criminal enterprise.',
        ideology: 'The Operators believe everything can be bought, sold, or negotiated. They value professionalism, profit, and presentation. They\'ll kill without hesitation if it\'s profitable, but they won\'t waste resources on pointless violence. They see themselves as businesspeople, not common thugs.',
        headquarters: ['Parlor (Nuka-World)'],
        notableMembers: ['Mags Black', 'William Black', 'Lizzie Wyath'],
        games: ['Fallout 4 (Nuka-World DLC)'],
        alignment: 'Neutral Evil',
        alignmentClass: 'alignment-hostile',
        strengths: ['Organized', 'Professional', 'Business acumen', 'Negotiation skills', 'Long-term planning'],
        weaknesses: ['Greedy', 'No loyalty beyond profit', 'Distrusted by other raiders', 'Calculating nature alienates allies']
    },
    {
        id: 'the-pack',
        name: 'The Pack',
        icon: '🐺',
        tagline: 'Run With the Pack',
        description: 'The Pack is one of three raider gangs in Nuka-World who have embraced an animal-themed identity. They paint themselves in bright colors, wear animal costumes, and organize themselves like a predator pack with an Alpha at the top.',
        history: 'The Pack formed when raiders adopted an animalistic philosophy, rejecting human civilization for pack mentality. They were drawn to Nuka-World\'s Safari Adventure zone and joined the coalition under Colter. They believe in strength, dominance hierarchies, and primal instincts.',
        ideology: 'The Pack rejects human society\'s rules in favor of animal instincts. The strong lead, the weak follow or die. They mark territory, challenge for dominance, and live in the moment. Their bright colors and costumes aren\'t costumes to them - they\'ve become their animal personas.',
        headquarters: ['Bradberton Amphitheater (Nuka-World)'],
        notableMembers: ['Mason', 'Various Pack members'],
        games: ['Fallout 4 (Nuka-World DLC)'],
        alignment: 'Chaotic Evil',
        alignmentClass: 'alignment-hostile',
        strengths: ['Pack tactics', 'Fearless', 'Physical strength', 'Animal ferocity', 'Group loyalty'],
        weaknesses: ['Primitive thinking', 'Challenge-based leadership unstable', 'Impulsive', 'Poor planning', 'Territorial disputes']
    },
    {
        id: 'trappers',
        name: 'The Trappers',
        icon: '🪤',
        tagline: 'The Fog Takes All',
        description: 'The Trappers are deranged former islanders on the Island (Far Harbor) who have been driven mad by the radioactive Fog. They now hunt and kill anyone who enters their territory, using brutal traps and ambush tactics. They are barely human anymore.',
        history: 'The Trappers were once normal residents of the Island who ventured too deep into the Fog without protection. The radiation and isolation drove them insane, transforming them into feral hunters. They\'ve lost most of their humanity, communicating in grunts and living like animals in the most Fog-shrouded regions.',
        ideology: 'The Trappers have no coherent ideology - they\'ve been reduced to predatory instincts by Fog madness. They hunt, kill, and sometimes cannibalize victims. They set elaborate traps and ambushes, showing cunning but no higher reasoning. The Fog is both their home and their religion.',
        headquarters: ['Various camps in Fog-heavy areas of The Island'],
        notableMembers: ['None notable - they\'ve lost individual identity'],
        games: ['Fallout 4 (Far Harbor DLC)'],
        alignment: 'Chaotic Evil',
        alignmentClass: 'alignment-hostile',
        strengths: ['Fog immunity', 'Trap expertise', 'Ambush tactics', 'Know the Island', 'No fear'],
        weaknesses: ['Insane', 'No organization', 'Can\'t leave Fog areas', 'Dwindling numbers', 'No allies']
    },
    {
        id: 'harbormen',
        name: 'Far Harbor',
        icon: '⚓',
        tagline: 'The Island Provides',
        description: 'Far Harbor is a settlement of hardy fishermen and their descendants who have survived for generations on the Island (Mount Desert Island, Maine). They live in constant conflict with the Fog, the Children of Atom, and the synths of Acadia.',
        history: 'Far Harbor has existed since before the war, surviving through fishing and isolation. As the Fog grew worse after the war, the settlement shrank to a single fortified town protected by Fog Condensers. They maintain an uneasy peace with Acadia but despise the Children of Atom who they believe are spreading the Fog.',
        ideology: 'The people of Far Harbor are survivalists who value self-reliance, hard work, and community. They distrust outsiders but will trade with them. They\'re practical people focused on daily survival rather than grand ideologies. Their main concerns are keeping the Fog at bay and maintaining their way of life.',
        headquarters: ['Far Harbor (The Island)'],
        notableMembers: ['Captain Avery', 'Allen Lee', 'Old Longfellow', 'Cassie Dalton', 'The Mariner'],
        games: ['Fallout 4 (Far Harbor DLC)'],
        alignment: 'True Neutral',
        alignmentClass: 'alignment-neutral',
        strengths: ['Survival expertise', 'Fortified position', 'Fishing industry', 'Community bonds', 'Fog Condensers'],
        weaknesses: ['Isolated', 'Dwindling population', 'Limited resources', 'Surrounded by enemies', 'Distrust of outsiders']
    },
    {
        id: 'acadia',
        name: 'Acadia',
        icon: '🏔️',
        tagline: 'A Place to Belong',
        description: 'Acadia is a refuge for runaway synths hidden in an observatory atop Mount Desert Island. Founded by DiMA, a prototype synth who escaped the Institute, it offers synths a place where they can live freely and discover their own identity.',
        history: 'DiMA, one of the first synths created by the Institute, escaped and eventually founded Acadia as a haven for others like him. He maintains a delicate balance between Far Harbor and the Children of Atom, keeping the peace through diplomacy and, when necessary, more questionable means. Acadia represents the possibility of synth self-determination.',
        ideology: 'Acadia believes synths deserve freedom, self-determination, and the right to define their own existence. Unlike the Railroad, which focuses on escape and assimilation, Acadia offers a community where synths can explore what it means to be synthetic. DiMA questions everything, including his own actions and memories.',
        headquarters: ['Acadia Observatory (Mount Desert Island)'],
        notableMembers: ['DiMA', 'Faraday', 'Chase', 'Kasumi Nakano'],
        games: ['Fallout 4 (Far Harbor DLC)'],
        alignment: 'Neutral Good',
        alignmentClass: 'alignment-friendly',
        strengths: ['Hidden location', 'DiMA\'s wisdom', 'Diplomatic neutrality', 'Technical expertise', 'Synth solidarity'],
        weaknesses: ['Small population', 'DiMA\'s secrets', 'Dependent on peace', 'Vulnerable to discovery', 'Internal doubts']
    },
    {
        id: 'atom-cats',
        name: 'Atom Cats',
        icon: '😎',
        tagline: 'Cool. Cats. Power Armor.',
        description: 'The Atom Cats are a greaser gang in the Commonwealth who have dedicated themselves to the appreciation and customization of Power Armor. They\'re non-hostile, laid-back, and just want to work on their armor and look cool doing it.',
        history: 'The Atom Cats settled in an old Red Rocket garage south of Boston, turning it into their headquarters and Power Armor workshop. Unlike most groups in the wasteland, they\'re not interested in conquest or ideology - just the pursuit of cool. They\'ll trade Power Armor parts and even share their expertise with friendly wastelanders.',
        ideology: 'The Atom Cats believe in being cool, customizing Power Armor, and not hassling people who don\'t hassle them. They\'ve got a strict no-squares policy and value style as much as substance. They see themselves as artists whose medium happens to be nuclear-powered exoskeletons.',
        headquarters: ['Atom Cats Garage'],
        notableMembers: ['Zeke', 'Rowdy', 'Duke', 'Bluejay', 'Johnny D'],
        games: ['Fallout 4'],
        alignment: 'Neutral Good',
        alignmentClass: 'alignment-friendly',
        strengths: ['Power Armor expertise', 'Custom modifications', 'Laid-back attitude', 'Trading partners', 'Technical skills'],
        weaknesses: ['Small group', 'Non-combative focus', 'Limited resources', 'Vulnerable location', 'Style over substance']
    }
];
